# Site settings
title: Angsters
email: theangsters@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Angsters is an instrumental trio from Belgrade, Serbia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://angste.rs" # the base hostname & protocol for your site
github_username:  klomontes
permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-postcss

sass:
  implementation: sass-embedded
  load_paths:
    - _sass

postcss:
  cache: false

exclude:
  - package.json
  - yarn.lock
  - tailwind.config.js
  - postcss.config.js
  - README.md
